sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

env:
  matrix:
    - SYMFONY_VERSION=2.3.*
    - SYMFONY_VERSION=2.7.*

matrix:
  fast_finish: true
  exclude:
    - php: 5.5
      env: SYMFONY_VERSION=2.7.*
    - php: 5.6
      env: SYMFONY_VERSION=2.7.*
  include:
    - php: 5.5
      env:
        - SYMFONY_VERSION=2.7.*
        - EXECUTE_CS_CHECK=true
    - php: 5.6
      env:
        - SYMFONY_VERSION=2.7.*
        - EXECUTE_TEST_COVERALLS=true

before_install:
  - phpenv config-rm xdebug.ini || return 0
  - composer self-update
  - if [[ $SYMFONY_VERSION != '' ]]; then composer require --dev --no-update symfony/symfony:${SYMFONY_VERSION} ; fi
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then composer require --dev --no-update satooshi/php-coveralls:dev-master ; fi

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then ./vendor/bin/phpunit --coverage-clover clover.xml ; fi
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then ./vendor/bin/phpunit ; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then vendor/bin/php-cs-fixer fix -v --dry-run; fi

after_script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then ./vendor/bin/coveralls ; fi
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then wget https://scrutinizer-ci.com/ocular.phar ; fi
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then php ocular.phar code-coverage:upload --format=php-clover clover.xml ; fi
