language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

env:
  - SYMFONY_VERSION=2.1
  - SYMFONY_VERSION=2.2
  - SYMFONY_VERSION=2.3

before_script:
   - bash .travis.sh
   - wget http://getcomposer.org/composer.phar
   - php composer.phar install --prefer-source

script: phpunit --configuration phpunit.travis.xml

